/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmacy;

import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.MouseEvent;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author egypt
 */
public class mainframe extends javax.swing.JFrame {

Double totalAmount=0.0;
    Double cash=0.0;
    Double balance=0.0;
    Double bHeight=0.0;
    
    ArrayList<String> itemName = new ArrayList<>();
    ArrayList<String> quantity = new ArrayList<>();
    ArrayList<String> itemPrice = new ArrayList<>();
    ArrayList<String> subtotal = new ArrayList<>();
    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        receipt = new javax.swing.JPanel();
        txtquantity = new javax.swing.JLabel();
        txtdate1 = new javax.swing.JLabel();
        txtdate = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        txtprice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablereceipt = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        quantitytxt = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jButton11 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        productlist = new javax.swing.JPanel();
        txtidpro = new javax.swing.JTextField();
        txtnamepro = new javax.swing.JTextField();
        txtpricepro = new javax.swing.JTextField();
        txtqunpro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        producttable = new javax.swing.JTable();
        pro_sec = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txtexpdata = new javax.swing.JTextField();
        txtprodata = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        agent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        agenttable = new javax.swing.JTable();
        r2 = new javax.swing.JRadioButton();
        r1 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        agen_password = new javax.swing.JTextField();
        agen_phone = new javax.swing.JTextField();
        agen_age = new javax.swing.JTextField();
        agen_name = new javax.swing.JTextField();
        agen_id = new javax.swing.JTextField();
        clearbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        adminpanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        adminusername = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        adminpassword = new javax.swing.JPasswordField();
        agenout = new javax.swing.JButton();
        mainframe = new javax.swing.JPanel();
        productlistbtn = new javax.swing.JButton();
        receiptbtn = new javax.swing.JButton();
        agentbtn = new javax.swing.JButton();
        logotbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        receipt.setBackground(new java.awt.Color(51, 51, 51));
        receipt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtquantity.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtquantity.setForeground(new java.awt.Color(68, 206, 255));
        txtquantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receipt.add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 240, 60));

        txtdate1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtdate1.setForeground(new java.awt.Color(68, 206, 255));
        txtdate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receipt.add(txtdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 320, 60));

        txtdate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtdate.setForeground(new java.awt.Color(68, 206, 255));
        txtdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receipt.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 340, 60));

        txtid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtid.setForeground(new java.awt.Color(68, 206, 255));
        txtid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receipt.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 102, 230, 30));

        txtprice.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtprice.setForeground(new java.awt.Color(68, 206, 255));
        txtprice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receipt.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 321, 240, 60));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(68, 206, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icons8-search-50.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        receipt.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 107, -1, -1));

        txt.setBackground(new java.awt.Color(51, 51, 51));
        txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt.setForeground(new java.awt.Color(255, 255, 255));
        txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt.setBorder(null);
        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKeyReleased(evt);
            }
        });
        receipt.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 110, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 206, 255));
        jLabel7.setText("total price : ");
        receipt.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        txttotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txttotal.setForeground(new java.awt.Color(68, 206, 255));
        txttotal.setText("0.0");
        receipt.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(68, 206, 255));
        jLabel1.setText("name");
        receipt.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(68, 206, 255));
        jLabel26.setText("Product id");
        receipt.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, -1, -1));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setForeground(new java.awt.Color(68, 206, 255));
        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        receipt.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 119, 70, -1));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setForeground(new java.awt.Color(68, 206, 255));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        receipt.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 119, -1, -1));

        tablereceipt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablereceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablereceiptMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablereceipt);

        receipt.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 1220, 180));
        receipt.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 148, 220, 15));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 206, 255));
        jLabel5.setText("quantity");
        receipt.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 169, -1, -1));

        quantitytxt.setBackground(new java.awt.Color(51, 51, 51));
        quantitytxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        quantitytxt.setForeground(new java.awt.Color(255, 255, 255));
        quantitytxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantitytxt.setBorder(null);
        quantitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytxtActionPerformed(evt);
            }
        });
        quantitytxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantitytxtKeyReleased(evt);
            }
        });
        receipt.add(quantitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 169, 220, 30));
        receipt.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 206, 217, 15));

        jButton11.setBackground(new java.awt.Color(51, 51, 51));
        jButton11.setForeground(new java.awt.Color(68, 206, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icons8-print-50.png"))); // NOI18N
        jButton11.setText("print");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        receipt.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 761, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/logo_1.png"))); // NOI18N
        receipt.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 205, -1, 509));

        getContentPane().add(receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1290, 840));

        productlist.setBackground(new java.awt.Color(51, 51, 51));
        productlist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtidpro.setBackground(new java.awt.Color(51, 51, 51));
        txtidpro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtidpro.setForeground(new java.awt.Color(255, 255, 255));
        txtidpro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtidpro.setBorder(null);
        txtidpro.setEnabled(false);
        txtidpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidproActionPerformed(evt);
            }
        });
        productlist.add(txtidpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 110, 167, 20));

        txtnamepro.setBackground(new java.awt.Color(51, 51, 51));
        txtnamepro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtnamepro.setForeground(new java.awt.Color(255, 255, 255));
        txtnamepro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnamepro.setBorder(null);
        txtnamepro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameproActionPerformed(evt);
            }
        });
        productlist.add(txtnamepro, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 259, 167, 20));

        txtpricepro.setBackground(new java.awt.Color(51, 51, 51));
        txtpricepro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpricepro.setForeground(new java.awt.Color(255, 255, 255));
        txtpricepro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpricepro.setBorder(null);
        txtpricepro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceproActionPerformed(evt);
            }
        });
        productlist.add(txtpricepro, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 380, 167, 20));

        txtqunpro.setBackground(new java.awt.Color(51, 51, 51));
        txtqunpro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtqunpro.setForeground(new java.awt.Color(255, 255, 255));
        txtqunpro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtqunpro.setBorder(null);
        txtqunpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqunproActionPerformed(evt);
            }
        });
        productlist.add(txtqunpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 500, 167, 20));

        producttable.setBackground(new java.awt.Color(51, 51, 51));
        producttable.setForeground(new java.awt.Color(68, 206, 255));
        producttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        producttable.setGridColor(new java.awt.Color(51, 51, 51));
        producttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                producttableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(producttable);

        productlist.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 719, 1290, 107));

        pro_sec.setBackground(new java.awt.Color(0, 0, 0,0));
        pro_sec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pro_sec.setForeground(new java.awt.Color(68, 206, 255));
        pro_sec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kids", "makup", "antipiotic", "skin care", " " }));
        pro_sec.setBorder(null);
        pro_sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pro_secActionPerformed(evt);
            }
        });
        productlist.add(pro_sec, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(68, 206, 255));
        jButton2.setText("add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        productlist.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 583, 79, 33));

        txtexpdata.setBackground(new java.awt.Color(51, 51, 51));
        txtexpdata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtexpdata.setForeground(new java.awt.Color(255, 255, 255));
        txtexpdata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtexpdata.setBorder(null);
        txtexpdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexpdataActionPerformed(evt);
            }
        });
        productlist.add(txtexpdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 154, -1));

        txtprodata.setBackground(new java.awt.Color(51, 51, 51));
        txtprodata.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtprodata.setForeground(new java.awt.Color(255, 255, 255));
        txtprodata.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtprodata.setBorder(null);
        txtprodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprodataActionPerformed(evt);
            }
        });
        productlist.add(txtprodata, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 110, 154, -1));

        jLabel3.setBackground(new java.awt.Color(68, 206, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 206, 255));
        jLabel3.setText("ID");
        productlist.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 110, 147, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 206, 255));
        jLabel9.setText("product name");
        productlist.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 206, 255));
        jLabel10.setText("price");
        productlist.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 380, 150, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(68, 206, 255));
        jLabel22.setText("quantity");
        productlist.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 500, 149, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(68, 206, 255));
        jLabel23.setText("Production Date");
        productlist.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(68, 206, 255));
        jLabel24.setText("expertion date");
        productlist.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(68, 206, 255));
        jLabel25.setText("Section");
        productlist.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, -1, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(68, 206, 255));
        jButton3.setText("update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        productlist.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 583, 79, 33));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(68, 206, 255));
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        productlist.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 583, 79, 33));
        productlist.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 136, 167, 10));
        productlist.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 285, 167, 10));
        productlist.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 406, 167, 10));
        productlist.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 526, 167, 10));
        productlist.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 165, 10));
        productlist.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 330, 165, 10));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/logo_1.png"))); // NOI18N
        productlist.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 205, -1, -1));

        getContentPane().add(productlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1290, 840));

        agent.setBackground(new java.awt.Color(51, 51, 51));
        agent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agenttable.setBackground(new java.awt.Color(51, 51, 51));
        agenttable.setForeground(new java.awt.Color(68, 206, 255));
        agenttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        agenttable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agenttableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(agenttable);

        agent.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 731, 1290, 102));

        r2.setBackground(new java.awt.Color(0, 0, 0,0));
        buttonGroup1.add(r2);
        r2.setForeground(new java.awt.Color(68, 206, 255));
        r2.setText("female");
        r2.setBorder(null);
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        agent.add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1143, 301, -1, -1));

        r1.setBackground(new java.awt.Color(0, 0, 0,0));
        buttonGroup1.add(r1);
        r1.setForeground(new java.awt.Color(68, 206, 255));
        r1.setText("male");
        r1.setBorder(null);
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        agent.add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1013, 301, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(68, 206, 255));
        jLabel14.setText("gender");
        agent.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 287, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(68, 206, 255));
        jLabel15.setText("password");
        agent.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 178, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(68, 206, 255));
        jLabel16.setText("phone");
        agent.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 71, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(68, 206, 255));
        jLabel13.setText("age");
        agent.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 301, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(68, 206, 255));
        jLabel12.setText("name");
        agent.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 194, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(68, 206, 255));
        jLabel2.setText("Id");
        agent.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 84, -1, -1));

        agen_password.setBackground(new java.awt.Color(51, 51, 51));
        agen_password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agen_password.setForeground(new java.awt.Color(255, 255, 255));
        agen_password.setBorder(null);
        agen_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agen_passwordActionPerformed(evt);
            }
        });
        agent.add(agen_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 177, 270, 30));

        agen_phone.setBackground(new java.awt.Color(51, 51, 51));
        agen_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agen_phone.setForeground(new java.awt.Color(255, 255, 255));
        agen_phone.setBorder(null);
        agen_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agen_phoneActionPerformed(evt);
            }
        });
        agent.add(agen_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 73, 270, 30));

        agen_age.setBackground(new java.awt.Color(51, 51, 51));
        agen_age.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agen_age.setForeground(new java.awt.Color(255, 255, 255));
        agen_age.setBorder(null);
        agen_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agen_ageActionPerformed(evt);
            }
        });
        agent.add(agen_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 300, 270, 30));

        agen_name.setBackground(new java.awt.Color(51, 51, 51));
        agen_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agen_name.setForeground(new java.awt.Color(255, 255, 255));
        agen_name.setBorder(null);
        agen_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agen_nameActionPerformed(evt);
            }
        });
        agent.add(agen_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 193, 270, 30));

        agen_id.setBackground(new java.awt.Color(51, 51, 51));
        agen_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agen_id.setForeground(new java.awt.Color(255, 255, 255));
        agen_id.setBorder(null);
        agen_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agen_idActionPerformed(evt);
            }
        });
        agent.add(agen_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 84, 270, 30));

        clearbtn.setBackground(new java.awt.Color(51, 51, 51));
        clearbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(68, 206, 255));
        clearbtn.setText("clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        agent.add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1049, 444, 89, -1));

        updatebtn.setBackground(new java.awt.Color(51, 51, 51));
        updatebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updatebtn.setForeground(new java.awt.Color(68, 206, 255));
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        agent.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 444, -1, -1));

        deletebtn.setBackground(new java.awt.Color(51, 51, 51));
        deletebtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deletebtn.setForeground(new java.awt.Color(68, 206, 255));
        deletebtn.setText("Delete");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        agent.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 444, 89, -1));

        addbtn.setBackground(new java.awt.Color(51, 51, 51));
        addbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addbtn.setForeground(new java.awt.Color(68, 206, 255));
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        agent.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 444, 89, -1));
        agent.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 120, 270, 10));
        agent.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 229, 270, 10));
        agent.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 336, 270, 10));
        agent.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 109, 270, 10));
        agent.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(998, 213, 270, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/logo_1.png"))); // NOI18N
        agent.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 221, -1, -1));

        adminpanel.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("admin login");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(68, 206, 255));
        jLabel18.setText("user name");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(68, 206, 255));
        jLabel19.setText("password");

        jButton12.setText("submit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminpanelLayout = new javax.swing.GroupLayout(adminpanel);
        adminpanel.setLayout(adminpanelLayout);
        adminpanelLayout.setHorizontalGroup(
            adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(adminpanelLayout.createSequentialGroup()
                        .addGroup(adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminusername)
                            .addComponent(adminpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminpanelLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        adminpanelLayout.setVerticalGroup(
            adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(adminusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(adminpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        agent.add(adminpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 390, 180));

        agenout.setBackground(new java.awt.Color(51, 51, 51));
        agenout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        agenout.setForeground(new java.awt.Color(255, 51, 51));
        agenout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icons8-exit-49.png"))); // NOI18N
        agenout.setText("logout");
        agenout.setBorder(null);
        agenout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenoutActionPerformed(evt);
            }
        });
        agent.add(agenout, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        getContentPane().add(agent, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1290, 830));

        mainframe.setBackground(new java.awt.Color(51, 51, 51));

        productlistbtn.setBackground(new java.awt.Color(51, 51, 51));
        productlistbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        productlistbtn.setForeground(new java.awt.Color(68, 206, 255));
        productlistbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icons8-product-50.png"))); // NOI18N
        productlistbtn.setText("product list");
        productlistbtn.setBorder(null);
        productlistbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productlistbtnActionPerformed(evt);
            }
        });

        receiptbtn.setBackground(new java.awt.Color(51, 51, 51));
        receiptbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        receiptbtn.setForeground(new java.awt.Color(68, 206, 255));
        receiptbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icons8-receipt-60.png"))); // NOI18N
        receiptbtn.setText("receipt");
        receiptbtn.setBorder(null);
        receiptbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptbtnActionPerformed(evt);
            }
        });

        agentbtn.setBackground(new java.awt.Color(51, 51, 51));
        agentbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        agentbtn.setForeground(new java.awt.Color(68, 206, 255));
        agentbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icons8-insurance-agent-50.png"))); // NOI18N
        agentbtn.setText("agent");
        agentbtn.setBorder(null);
        agentbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agentbtnMouseClicked(evt);
            }
        });
        agentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentbtnActionPerformed(evt);
            }
        });

        logotbtn.setBackground(new java.awt.Color(51, 51, 51));
        logotbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        logotbtn.setForeground(new java.awt.Color(68, 206, 255));
        logotbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/icons8-exit-49.png"))); // NOI18N
        logotbtn.setText("log out");
        logotbtn.setBorder(null);
        logotbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logotbtnActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/logo_1.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pharmacy/line.png"))); // NOI18N

        javax.swing.GroupLayout mainframeLayout = new javax.swing.GroupLayout(mainframe);
        mainframe.setLayout(mainframeLayout);
        mainframeLayout.setHorizontalGroup(
            mainframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainframeLayout.createSequentialGroup()
                .addGroup(mainframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainframeLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(mainframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productlistbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receiptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logotbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainframeLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(400, 400, 400)
                .addComponent(jLabel4))
        );
        mainframeLayout.setVerticalGroup(
            mainframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainframeLayout.createSequentialGroup()
                .addGroup(mainframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainframeLayout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(receiptbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainframeLayout.createSequentialGroup()
                        .addGap(585, 585, 585)
                        .addComponent(logotbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainframeLayout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(agentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainframeLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(productlistbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainframeLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(186, 186, 186))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainframeLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );

        getContentPane().add(mainframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
        agenout.setVisible(false);
        agen_name.setEnabled(false);
            agen_age.setEnabled(false);
            agen_password.setEnabled(false);
            agen_phone.setEnabled(false);
            addbtn.setEnabled(false);
            deletebtn.setEnabled(false);
            clearbtn.setEnabled(false);
            updatebtn.setEnabled(false);
            agen_id.setEnabled(false);
//        Bill_Text.setText(        "                                                             *************************************PharmaCenter***************************************\n" +
//"                          	                                                                  ID    MEDICINE    QUANTITY    PRICE    TOTAL");
        productlist.setVisible(false);
        receipt.setVisible(false);
       
        agent.setVisible(false);
         
         try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("select * from products");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Id");
            dm.addColumn("Name");
            dm.addColumn("price");
            dm.addColumn("Quantity");
            dm.addColumn("production_data");
            dm.addColumn("expertion_data");
            dm.addColumn("section");
            while(set.next()){
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7)};
                dm.addRow(r);
            }
                producttable.setModel(dm);
            
        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
          
      
          
    }//GEN-LAST:event_formWindowOpened

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionPerformed
private void clear(){
     agen_name.setText("");
    agen_age.setText("");
    agen_phone.setText("");
    agen_password.setText("");
    r1.setSelected(false);
    r2.setSelected(false);
    agen_id.setText("");
}

String price;
String production;
String expertion;
private double totalprice(){
    double total_price = 0 ;
    total_price +=  Double.parseDouble(price);
    return total_price;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            Statement stmt= con.prepareStatement("select * from products where pro_name = '"+txt.getText()+"' ");
            ResultSet set = stmt.executeQuery("select * from products where pro_name = '"+txt.getText()+"' ");
          
            if(set.next()){
              
                price=set.getString(3);
                production=set.getString(5);
                expertion=set.getString(6);
                txtid.setText(set.getString(1));
                txtprice.setText( "price : " + price+" LE" );
                txtdate.setText("production date : " + production );
                txtquantity.setText(set.getString(4) + " pices");
                txtdate1.setText( "expertion date : " + expertion);
            }
            else{
                JOptionPane.showMessageDialog(null, "sorry !No data found for this ID");
                txt.setText("");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyReleased
        // TODO add your handling code here:
        txtid.setText("");
        txtprice.setText("");
        txtdate.setText("");
        txtdate1.setText("");
        txtquantity.setText("");
    }//GEN-LAST:event_txtKeyReleased

    private void txtexpdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexpdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexpdataActionPerformed

    private void pro_secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pro_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pro_secActionPerformed

    private void producttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_producttableMouseClicked
        // TODO add your handling code here:
        int curentrow;
        curentrow=producttable.getSelectedRow();
        txtidpro.setText(producttable.getValueAt(curentrow, 0).toString());
        txtnamepro.setText(producttable.getValueAt(curentrow, 1).toString());
        txtpricepro.setText(producttable.getValueAt(curentrow, 2).toString());
        txtqunpro.setText(producttable.getValueAt(curentrow, 3).toString());
        txtprodata.setText(producttable.getValueAt(curentrow, 4).toString());
        txtexpdata.setText(producttable.getValueAt(curentrow, 5).toString());
    }//GEN-LAST:event_producttableMouseClicked

    private void txtqunproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqunproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqunproActionPerformed

    private void txtpriceproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceproActionPerformed

    private void txtnameproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameproActionPerformed

    private void txtidproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidproActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("insert into products(pro_name,pro_price,pro_quantity,pro_productiondate,pro_expertiondate,pro_sec)values(?,?,?,?,?,?)");
            stmt.setString(1, txtnamepro.getText());
            stmt.setString(2, txtpricepro.getText());
            stmt.setString(3, txtqunpro.getText());
            stmt.setString(4, txtprodata.getText());
            stmt.setString(5, txtexpdata.getText());
            stmt.setString(6, pro_sec.getSelectedItem().toString());
            stmt.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("select * from products");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Id");
            dm.addColumn("Name");
            dm.addColumn("price");
            dm.addColumn("Quantity");
            dm.addColumn("production_data");
            dm.addColumn("expertion_data");
            dm.addColumn("section");
            while(set.next()){
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7)};
                dm.addRow(r);
            }
            producttable.setModel(dm);

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("update products set pro_name=? ,pro_price=?,pro_quantity=?,pro_productiondate=?,pro_expertiondate=?,pro_sec=? where pro_id=?");
            stmt.setString(1, txtnamepro.getText());
            stmt.setString(2, txtpricepro.getText());
            stmt.setString(3, txtqunpro.getText());
            stmt.setString(4, txtprodata.getText());
            stmt.setString(5, txtexpdata.getText());
            stmt.setString(6, pro_sec.getSelectedItem().toString());
            stmt.setString(7, txtidpro.getText());
            stmt.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("select * from products");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Id");
            dm.addColumn("Name");
            dm.addColumn("price");
            dm.addColumn("Quantity");
            dm.addColumn("production_data");
            dm.addColumn("expertion_data");
            dm.addColumn("section");
            while(set.next()){
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7)};
                dm.addRow(r);
            }
            producttable.setModel(dm);

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
          try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("delete from products where pro_id=?");

            stmt.setString(1, txtidpro.getText());
            stmt.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("select * from products");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Id");
            dm.addColumn("Name");
            dm.addColumn("price");
            dm.addColumn("Quantity");
            dm.addColumn("production_data");
            dm.addColumn("expertion_data");
            dm.addColumn("section");
            while(set.next()){
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6),set.getString(7)};
                dm.addRow(r);
            }
            producttable.setModel(dm);

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        // TODO add your handling code here:int i=1;
//معرف السعر فوق فالجدول
DefaultTableModel model =(DefaultTableModel)tablereceipt.getModel();
model.addRow(new Object[]{txtid.getText(),txt.getText(),quantitytxt.getText(),txtprice.getText()});
   float x =Float.parseFloat(price)*Float.parseFloat( quantitytxt.getText());
//    Bill_Text.setText(
//
//        Bill_Text.getText()+"\n"
//        + "                                                                                        "+txtid.getText()+"      "+txt.getText()+"           "+quantitytxt.getText()+"              "+txtprice.getText()+"       "+x);
    float n = Float.parseFloat(txttotal.getText())+x;
        txttotal.setText(n+"");
        
        
        itemName.add(txt.getText());
        quantity.add(quantitytxt.getText());
        itemPrice.add(txtprice.getText());
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
//        txttotal.setText(0.0+"");
//        Bill_Text.setText(        "                                                             *************************************PharmaCenter***************************************\n" +
//"                          	                                                                  ID    MEDICINE    QUANTITY    PRICE    TOTAL");
//       
DefaultTableModel model =(DefaultTableModel)tablereceipt.getModel();
int current = tablereceipt.getSelectedRow();
model.removeRow(current);

    }//GEN-LAST:event_jButton6ActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("insert into agent(agen_name,agen_age,agen_phone,agen_password,agen_gender)values(?,?,?,?,?)");
            stmt.setString(1, agen_name.getText());
            stmt.setString(2, agen_age.getText());
            stmt.setString(3, agen_phone.getText());
            stmt.setString(4, agen_password.getText());
            String agent = null;
            if(r1.isSelected()==true){
                agent="male";
            }
            else if(r2.isSelected()==true){
                agent="female";
            }
            stmt.setString(5, agent);
            stmt.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("select * from agent");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Id");
            dm.addColumn("Name");
            dm.addColumn("age");
            dm.addColumn("phone");
            dm.addColumn("password");
            dm.addColumn("gender");

            while(set.next()){
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6)};
                dm.addRow(r);
            }
            agenttable.setModel(dm);

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear();
    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("delete from agent where agen_id=?");

            stmt.setString(1, agen_id.getText());
            stmt.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("select * from agent");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Id");
            dm.addColumn("Name");
            dm.addColumn("age");
            dm.addColumn("phone");
            dm.addColumn("password");
            dm.addColumn("gender");

            while(set.next()){
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6)};
                dm.addRow(r);
            }
            agenttable.setModel(dm);

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear();
    }//GEN-LAST:event_deletebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:

        try {
            // TODO add your handling code here:agen_name,agen_age,agen_phone,agen_password,agen_gender
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("update agent set agen_name=? ,agen_age=?,agen_phone=?,agen_password=?,agen_gender=? where agen_id=?");
            stmt.setString(1, agen_name.getText());
            stmt.setString(2, agen_age.getText());
            stmt.setString(3, agen_phone.getText());
            stmt.setString(4, agen_password.getText());
            String agent = null;
            if(r1.isSelected()==true){
                agent="male";
            }
            else if(r2.isSelected()==true){
                agent="female";
            }
            stmt.setString(5, agent);
            stmt.setString(6, agen_id.getText());
            stmt.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("select * from agent");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Id");
            dm.addColumn("Name");
            dm.addColumn("age");
            dm.addColumn("phone");
            dm.addColumn("password");
            dm.addColumn("gender");

            while(set.next()){
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6)};
                dm.addRow(r);
            }
            agenttable.setModel(dm);

        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
        clear();
    }//GEN-LAST:event_updatebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearbtnActionPerformed

    private void agen_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agen_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agen_idActionPerformed

    private void agen_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agen_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agen_nameActionPerformed

    private void agen_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agen_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agen_ageActionPerformed

    private void agen_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agen_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agen_phoneActionPerformed

    private void agen_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agen_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agen_passwordActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    private void agenttableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agenttableMouseClicked
        // TODO add your handling code here:
        int curentrow;

        curentrow=agenttable.getSelectedRow();
        agen_id.setText(agenttable.getValueAt(curentrow, 0).toString());
        agen_name.setText(agenttable.getValueAt(curentrow, 1).toString());
        agen_age.setText(agenttable.getValueAt(curentrow, 2).toString());
        agen_phone.setText(agenttable.getValueAt(curentrow, 3).toString());
        agen_password.setText(agenttable.getValueAt(curentrow, 4).toString());
        if ("male".equals(agenttable.getValueAt(curentrow, 5).toString())){
            r1.setSelected(true);
        }
        else{
            r2.setSelected(true);
        }
    }//GEN-LAST:event_agenttableMouseClicked

    private void logotbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logotbtnActionPerformed
        // TODO add your handling code here:
        System.exit(WIDTH);
    }//GEN-LAST:event_logotbtnActionPerformed

    private void agentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentbtnActionPerformed
        // TODO add your handling code here:  // TODO add your handling code here:
        productlist.setVisible(false);
        receipt.setVisible(false);
        agent.setVisible(true);
    }//GEN-LAST:event_agentbtnActionPerformed

    private void agentbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agentbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_agentbtnMouseClicked

    private void receiptbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptbtnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        productlist.setVisible(false);
        receipt.setVisible(true);

        agent.setVisible(false);
    }//GEN-LAST:event_receiptbtnActionPerformed

    private void productlistbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productlistbtnActionPerformed
        // TODO add your handling code here:        // TODO add your handling code here:
        productlist.setVisible(true);
        receipt.setVisible(false);

        agent.setVisible(false);
    }//GEN-LAST:event_productlistbtnActionPerformed

    private void quantitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytxtActionPerformed

    private void quantitytxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantitytxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytxtKeyReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        
         PrinterJob pj = PrinterJob.getPrinterJob();        
        pj.setPrintable(new BillPrintable(),getPageFormat(pj));
        try {
             pj.print();
          
        }
         catch (PrinterException ex) {
                 ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    String adminUserName;
    String adminPassword;
    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if(adminusername.getText().equalsIgnoreCase("admin")&&adminpassword.getText().equals("admin"))
        {
            try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy","root","root");
            PreparedStatement stmt= con.prepareStatement("select * from agent");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            dm.addColumn("Id");
            dm.addColumn("Name");
            dm.addColumn("age");
            dm.addColumn("phone");
            dm.addColumn("password");
            dm.addColumn("gender");
           
            while(set.next()){
                String r[]={set.getString(1),set.getString(2),set.getString(3),set.getString(4),set.getString(5),set.getString(6)};
                dm.addRow(r);
            }
                agenttable.setModel(dm);
            
        } catch (SQLException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
            adminusername.setText("");
            adminpassword.setText("");
            agen_name.setEnabled(true);
            agen_age.setEnabled(true);
            agen_password.setEnabled(true);
            agen_phone.setEnabled(true);
            addbtn.setEnabled(true);
            deletebtn.setEnabled(true);
            clearbtn.setEnabled(true);
            updatebtn.setEnabled(true);
            adminpanel.setVisible(false);
            agenout.setVisible(true);
            agenttable.setVisible(true);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void agenoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agenoutActionPerformed
        // TODO add your handling code here:
        agen_name.setEnabled(false);
            agen_age.setEnabled(false);
            agen_password.setEnabled(false);
            agen_phone.setEnabled(false);
            addbtn.setEnabled(false);
            deletebtn.setEnabled(false);
            clearbtn.setEnabled(false);
            updatebtn.setEnabled(false);
            adminpanel.setVisible(true);
            agenout.setVisible(false);
            agenttable.setVisible(false);
    }//GEN-LAST:event_agenoutActionPerformed

      public PageFormat getPageFormat(PrinterJob pj)
{
    
    PageFormat pf = pj.defaultPage();
    Paper paper = pf.getPaper();    

    double bodyHeight = bHeight;  
    double headerHeight = 5.0;                  
    double footerHeight = 5.0;        
    double width = cm_to_pp(8); 
    double height = cm_to_pp(headerHeight+bodyHeight+footerHeight); 
    paper.setSize(width, height);
    paper.setImageableArea(0,10,width,height - cm_to_pp(1));  
            
    pf.setOrientation(PageFormat.PORTRAIT);  
    pf.setPaper(paper);    

    return pf;
}
   
    
    
    protected static double cm_to_pp(double cm)
    {            
	        return toPPI(cm * 0.393600787);            
    }
 
protected static double toPPI(double inch)
    {            
	        return inch * 72d;            
    }
    


public class BillPrintable implements Printable {
    
   
    
    
  public int print(Graphics graphics, PageFormat pageFormat,int pageIndex) 
  throws PrinterException 
  {    
      
      int r= itemName.size();
      ImageIcon icon=new ImageIcon("C:\\Users\\egypt\\OneDrive\\Documents\\NetBeansProjects\\receipt\\src\\main\\java\\logo_1.png"); 
      int result = NO_SUCH_PAGE;    
        if (pageIndex == 0) {                    
        
            Graphics2D g2d = (Graphics2D) graphics;                    
            double width = pageFormat.getImageableWidth();                               
            g2d.translate((int) pageFormat.getImageableX(),(int) pageFormat.getImageableY()); 



          //  FontMetrics metrics=g2d.getFontMetrics(new Font("Arial",Font.BOLD,7));
        
        try{
            int y=20;
            int yShift = 10;
            int headerRectHeight=15;
           // int headerRectHeighta=40;
            
                
            g2d.setFont(new Font("Monospaced",Font.PLAIN,9));
            g2d.drawImage(icon.getImage(), 50, 20, 90, 30, rootPane);y+=yShift+30;
            g2d.drawString("-------------------------------------",12,y);y+=yShift;
            g2d.drawString("         CodeGuid.com        ",12,y);y+=yShift;
            g2d.drawString("   No 00000 Address Line One ",12,y);y+=yShift;
            g2d.drawString("   Address Line 02 SRI LANKA ",12,y);y+=yShift;
            g2d.drawString("   www.facebook.com/CodeGuid ",12,y);y+=yShift;
            g2d.drawString("        +94700000000      ",12,y);y+=yShift;
            g2d.drawString("-------------------------------------",12,y);y+=headerRectHeight;

            g2d.drawString(" Item Name                  Price   ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------",10,y);y+=headerRectHeight;
     
            for(int s=0; s<r; s++)
            {
            g2d.drawString(" "+itemName.get(s)+"                            ",10,y);y+=yShift;
            g2d.drawString("      "+quantity.get(s)+" * "+itemPrice.get(s),10,y); g2d.drawString(subtotal.get(s),160,y);y+=yShift;

            }
          
            g2d.drawString("-------------------------------------",10,y);y+=yShift;
            g2d.drawString(" Total amount:               "+"   ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------",10,y);y+=yShift;
            g2d.drawString(" Cash      :                 "+"   ",10,y);y+=yShift;
            g2d.drawString("-------------------------------------",10,y);y+=yShift;
            g2d.drawString(" Balance   :                 "+"   ",10,y);y+=yShift;
  
            g2d.drawString("*************************************",10,y);y+=yShift;
            g2d.drawString("       THANK YOU COME AGAIN            ",10,y);y+=yShift;
            g2d.drawString("*************************************",10,y);y+=yShift;
            g2d.drawString("         SOFTWARE BY:ABDO            ",10,y);y+=yShift;
            g2d.drawString("        CONTACT: contactus             ",10,y);y+=yShift;       
           

    }
    catch(Exception e){
    e.printStackTrace();
    }

              result = PAGE_EXISTS;    
          }    
          return result;    
      }
   }
    
    private void txtprodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprodataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprodataActionPerformed

    private void tablereceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablereceiptMouseClicked
        // TODO add your handling code here:
         int curentrow;
        curentrow=tablereceipt.getSelectedRow();
    }//GEN-LAST:event_tablereceiptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JPanel adminpanel;
    private javax.swing.JPasswordField adminpassword;
    private javax.swing.JTextField adminusername;
    private javax.swing.JTextField agen_age;
    private javax.swing.JTextField agen_id;
    private javax.swing.JTextField agen_name;
    private javax.swing.JTextField agen_password;
    private javax.swing.JTextField agen_phone;
    private javax.swing.JButton agenout;
    private javax.swing.JPanel agent;
    private javax.swing.JButton agentbtn;
    private javax.swing.JTable agenttable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton logotbtn;
    private javax.swing.JPanel mainframe;
    private javax.swing.JComboBox<String> pro_sec;
    private javax.swing.JPanel productlist;
    private javax.swing.JButton productlistbtn;
    private javax.swing.JTable producttable;
    private javax.swing.JTextField quantitytxt;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JPanel receipt;
    private javax.swing.JButton receiptbtn;
    private javax.swing.JTable tablereceipt;
    private javax.swing.JTextField txt;
    private javax.swing.JLabel txtdate;
    private javax.swing.JLabel txtdate1;
    private javax.swing.JTextField txtexpdata;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtidpro;
    private javax.swing.JTextField txtnamepro;
    private javax.swing.JLabel txtprice;
    private javax.swing.JTextField txtpricepro;
    private javax.swing.JTextField txtprodata;
    private javax.swing.JLabel txtquantity;
    private javax.swing.JTextField txtqunpro;
    private javax.swing.JLabel txttotal;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables

    private void jButton1ActionPerformed(MouseEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private String toString(double totalprice) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
